language: cpp
dist: trusty
sudo: false
compiler: clang++
os: osx
osx_image: xcode9.4
before_install:
  - brew update && brew bundle
before_script:
  - cmake -B./build -H.
script:
  - cmake --build ./build --config Debug --target all -- -j2
  - cd build
  - ctest -j2 -C Debug -T test --output-on-failure
notifications:
  email:
    false