language: cpp
dist: trusty
sudo: false
compiler: clang++
os: osx
osx_image: xcode9.4
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.emscripten_cache
    - $HOME/.emscripten_ports
before_install:
  - brew update && brew bundle
before_script:
  - nvm install node
  - emcc -v
  - LLVM=/usr/local/opt/emscripten/libexec/llvm/bin cmake -DBOOST_ROOT=/usr/local/opt/boost -DCMAKE_TOOLCHAIN_FILE=/usr/local/opt/emscripten/libexec/cmake/Modules/Platform/Emscripten.cmake -B./build -H.
script:
  - LLVM=/usr/local/opt/emscripten/libexec/llvm/bin cmake --build ./build --config Debug --target all -- -j2
  - cd build
  - ctest -j2 -C Debug -T test --output-on-failure
notifications:
  email:
    false