language: cpp
dist: trusty
sudo: false
compiler: clang++
os: osx
osx_image: xcode10.2
before_install:
  - brew update && brew bundle
before_script:
  - nvm install node
  - emcc -v
  - node tools/macos-emscripten-configure.js
script:
  - node tools/macos-run-static-analyzer.js
  - node tools/macos-emscripten-build.js
  - node tools/macos-run-test.js
notifications:
  email:
    false